# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-16 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('repository', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64)),
                ('featured', models.BooleanField(default=False)),
                ('readme', models.TextField(blank=True, help_text='Please update this on github!')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sha', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at', models.DateTimeField()),
                ('download_url', models.URLField(blank=True)),
                ('language', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('username', 'repository')]),
        ),
    ]
