# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0004_delete_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='watched',
        ),
    ]
