# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0005_remove_project_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='repository',
            field=models.CharField(default='penis', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='username',
            field=models.CharField(default='dick', max_length=128),
            preserve_default=False,
        ),
    ]
