# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0006_auto_20151216_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
