# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0007_auto_20151216_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='readme',
        ),
    ]
