# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linker', '0009_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
